name: TPAll
main: matymare\tpall\Main
version: 1.3
api: 4.0.0
author: matymare
description: Teleport all player to you!

commands:
  tpall:
    description: Teleport all players to you!
    usage: "/tpall"
    permission: tpall.command

permissions:
  tpall.command:
    description: Permission for /tpall command.
    default: op